files: ./src/index.pug
run: pug -P %file% -o .
---
files: ./src/articles/*.pug
run: pug -P %file% -o ./articles/
---
files: ./src/*.styl
run: stylus %file% -o .
---
files: ./src/showcase/*.pug
run: pug -P %file% -o ./showcase/